name: test
on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2

      - name: run
        uses: ./
        with:
          poll-interval-seconds: 60
          continue-after-seconds: 10
          # abort-after-seconds: 10
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: run
        run: |
          echo "worked!"
